<div id="home" class="jumbotron starter-template">
    <h1>Phalcon modules skeleton</h1>
    <p class="lead">Easy way to start your new project.</p>
    <p><a class="btn btn-lg btn-success" href="https://github.com/ovr/phalcon-module-skeleton" target="_blank">Исходный код на Github</a></p>
</div>
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Main futures</h2>
    </div>
    <div class="col-md-6">
        <p>The project consists and include:</p>
        <ul>
            <li><strong>Modules structure with preinstalled modules</strong>
            <li>Easy application bootstrapping</li>
            <li>Full frontend developer stuck composer/npm/bower/gulp</li>
            <li><strong>Design is builded by Bootstrap v3.2.0</strong>
            </li>
            <li>Console task support (provided by symfony/console)</li>
            <li>Error handling (not found router, dispatcher exceptions)</li>
            <li>Shared layouts and services</li>
        </ul>
        <p>This is a skeleton application written on phalcon framework with performance boost. This project created to develop applications in easy way.</p>
    </div>
    <div class="col-md-6">
        <img class="img-responsive" src="http://placehold.it/700x450" alt="">
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <legend><h2 class="text-center">Предустановленные модули</h2></legend>
    </div>
</div>