<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Dmitry Patsura">

    <title>Phalcon module skeleton</title>

    <link href="/dist/all.css" rel="stylesheet">
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Phalcon module skeleton</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <?php
                        $uri = $this->getDi()->getShared('request')->getUri();
                    ?>
                    <li<?php echo ($uri == '/') ? ' class="active"' : ''; ?>>
                        <a href="/">Home</a>
                    </li>
                    <li<?php echo ($uri == '/frontend/index/getting-started/') ? ' class="active"' : ''; ?>>
                        <a href="/frontend/index/getting-started/">Getting started</a>
                    </li>
                    <li<?php echo ($uri == '/frontend/pretty-exception/') ? ' class="active"' : ''; ?>>
                        <a href="/frontend/pretty-exception/">Pretty Exception</a>
                    </li>
                    <li<?php echo ($uri == '/catalog') ? ' class="active"' : ''; ?>>
                        <a href="/catalog">Catalog</a>
                    </li>
                    <li><a href="/admin">Admin</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>

    <div class="container">
        <?php echo $this->getContent(); ?>

        <?php echo $this->partial('footer'); ?>
    </div>
</body>
</html>