<div class="row">
    <!-- LEFT SIDE CATEGORIES-->
    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
        <div class="panel panel-default visible-lg">
            <div class="panel-heading">
                <h4>Categories</h4>
            </div>
            <div class="panel-body">
                <ul id="cat-navi2" class="nav nav-list ">
                    <?php foreach ($categories as $category) : ?>
                        <li><a href="/catalog/category/<?php echo $category->id; ?>/"><?php echo $category->title; ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>

        <!-- panel OFFER-->
        <div class="visible-lg">
            <div class="panel panel-success text-center">
                <div class="panel-body">
                    <p class="lead"> SPECIAL OFFER DISCOUNT -20% </p>
                </div>
            </div>
        </div>
        <!-- / panel OFFER-->

        <!-- panel OFFER-->
        <div class="visible-lg">
            <div class="panel panel-success text-center">
                <div class="panel-body">
                    <p class="lead"> SPECIAL OFFER DISCOUNT -20% </p>
                </div>
            </div>
        </div>
        <!-- / panel OFFER-->

        <!-- panel OFFER-->
        <div class="visible-lg">
            <div class="panel panel-success text-center">
                <div class="panel-body">
                    <p class="lead"> SPECIAL OFFER DISCOUNT -20% </p>
                </div>
            </div>
        </div>
        <!-- / panel OFFER-->

        <!-- panel OFFER-->
        <div class="visible-lg">
            <div class="panel panel-success text-center">
                <div class="panel-body">
                    <p class="lead"> SPECIAL OFFER DISCOUNT -20% </p>
                </div>
            </div>
        </div>
        <!-- / panel OFFER-->

    </div>
    <!-- /left SIDE-->

    <!-- CONTENT SIDE-->
    <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
        <?php foreach ($products as $product) : ?>
            <div class="container-folio row">
                <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">
                    <div class="thumbnail">
                        <img src="http://placehold.it/250x250" alt="post image">
                        <div class="caption">
                            <h3 class=""><?php echo $product->title; ?></h3>
                            <p class="">This project presents beautiful style graphic &amp; design. Bootstraptor provides modern features</p>

                            <div class="row">
                                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                    <p class="lead">$<?php echo $product->price; ?></p>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                    <a class="btn btn-success btn-block" href="#">Add to cart</a>
                                </div>
                            </div>
                        </div>
                        <!--END CAPTION -->
                    </div>
                    <!-- END: THUMBNAIL -->
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>